# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
      # Check for npm updates on Mondays at 9am UTC
      day: "monday"
      time: "09:00"
    allow:
      - dependency-name: "chalk"
      - dependency-name: "tmi.js"
      - dependency-name: "dotenv"
   assignees:
        - "carmoruda"
   commit-message:
        - prefix: ":arrow_up:"
        - include: "scope"
