name: Help request
description: Request help with an issue you are having
title: "[Help request]: "
labels: ["help wanted"]
assignees:
  - Carmoruda
body:
  - type: textarea
  id: help-request
  attributes:
    label: Help Request
    description: Enter a clear and concise explanation of the issue you are having or the thing you would like help with.
    placeholder: Ex. I'm having a problem with the [...]
  validations:
    required: false
  - type: textarea
      attributes:
        label: Environment
        description: |
          Example:
            - **OS**: Ubuntu 20.04
            - **Node**: 13.14.0
            - **npm**: 7.6.3
        value: |
            - OS:
            - Node:
            - npm:
        render: markdown
      validations:
        required: false
